### ISSUE TITLE
Similar project rec2json

### ISSUE THREAD

**Issue by joaohf** [jonasrichard/ejson#49]
Hi,

What is the difference between ejson and https://github.com/lordnull/rec2json ?

I think that both projects has many common points. Maybe brings the best of rec2json to ejson?

Thanks.

**Comment by jonasrichard** [comment]
How come that I haven't got a notification about your question? Anyway.
The difference is that rec2json converts based on dialyzer type specs. When I started to implement ejson I had the same idea but sometimes you want to generate values in json which is a result of a computation (derived field, pre_encode, post_decode hooks). Sometimes you don't want to serialize the data in that form in which you store them in the model (os:timestamp() vs javascript timestamp). Sometimes you want to skip a value from json, or add a completely new value to json representation.

In ejson you rather specify rules how to convert your data to json, but it doesn't belong to the record definition. Moreover, you don't even need to have a record definition in order to convert some tuples into records. I think it is much more flexible. I want to add rebar3 support and more examples.

**Comment by joaohf** [comment]
Hi,

I agree. Today I used pre and post encode.

Great library.
